services:
  api:
    build: ./api
    ports:
      - 4000:4000
    command: npm run prod
    restart: always
    environment:
      - CLIENT_URL=http://localhost:4173
      - PORT=4000

  client:
    build: ./client
    command: npm run preview
    restart: always
    env_file:
      - ./client/.env
    ports:
      - 4173:4173
